// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// sgl_to_rgs
Rcpp::List sgl_to_rgs(std::string sgl_stmt);
RcppExport SEXP _rsgl_sgl_to_rgs(SEXP sgl_stmtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type sgl_stmt(sgl_stmtSEXP);
    rcpp_result_gen = Rcpp::wrap(sgl_to_rgs(sgl_stmt));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rsgl_sgl_to_rgs", (DL_FUNC) &_rsgl_sgl_to_rgs, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_rsgl(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
