# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sgl_to_rgs <- function(sgl_stmt) {
    .Call(`_rsgl_sgl_to_rgs`, sgl_stmt)
}

